# Generated by Django 5.0.6 on 2024-05-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='name',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='description',
            new_name='theatre',
        ),
    ]
