# Generated by Django 5.0.6 on 2024-05-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_rename_name_detail_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='theatre',
            field=models.CharField(max_length=100),
        ),
    ]
